module.exports = {
  ESTADOS_SOLICITUD: {
    NUEVA: "NUEVA",
    PENDIENTE: "PENDIENTE",
    APROBADA: "APROBADA",
    IMPRESA: "IMPRESA",
    DESPACHADA: "DESPACHADA",
    VENCIDA: "VENCIDA",
    ANULADA: "ANULADA",
    FINALIZADA: "FINALIZADA",
  },

  TIPOS_SUMINISTRO: {
    BIDON: "BIDON",
    REGULAR: "REGULAR",
  },

  TIPOS_SOLICITUD: {
    VENTA: "VENTA",
    ASIGNACION: "ASIGNACION",
  },

  PREFIJOS_TICKET: {
    BIDON: "B",
    REGULAR: "R",
  },
};
